name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  dio: ^5.7.0
  dartz: ^0.10.1
  logger: ^2.4.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_otp_text_field: ^1.2.0
  otp_text_field: ^1.1.3
  pin_code_fields: ^8.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


